### PR TITLE
feat(externals): add react-is to global externals

### PR DESCRIPTION
**Pull request by Matthew-Mallimo**
#### Check boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

#### Check boxes that apply:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

### CODE REVIEW

**Comment by Matthew-Mallimo** [comment]
Closing for now as this would require a new one-app version, and would tie a one-app version to a bundler version

**Comment by 10xLaCroixDrinker** [comment]
Should we include this in v6?

**Comment by Matthew-Mallimo** [comment]
> Should we include this in v6?

We can, but it will require a major version of the bundler as well

**Comment by Matthew-Mallimo** [comment]
> Should we include this in v6?

The benefit is very minimal, only ~3kb savings in the bundle. But yeah we should include it in v6

**Pull request closed without merging**
